# GESTION DES SHORTCODES 
## Mettre à false pour désactiver
shortcodes:
  woocommerce_cart:           true
  woocommerce_checkout:       true
  woocommerce_order_tracking: true
  woocommerce_my_account:     true

# CHARGEMENT DES SCRIPTS
script_loader:
  ## Chargement des Feuilles de styles natives Woocommerce
  wc_enqueue_styles:
    woocommerce-layout:         true
    woocommerce-smallscreen:    true
    woocommerce-general:        true
  
  ## Chargement des Scripts JS natifs Woocommerce  
  wc_enqueue_scripts:
    wc-address-i18n:            true
    wc-add-payment-method:      true
    wc-cart:                    true
    wc-cart-fragments:          true
    wc-checkout:                true
    wc-country-select:          true
    wc-credit-card-form:        true
    wc-add-to-cart:             true
    wc-add-to-cart-variation:   true
    wc-geolocation:             true
    wc-lost-password:           true
    wc-password-strength-meter: true
    wc-single-product:          true
    woocommerce:                true 

# ACCROCHAGE / DECROCHAGE / RE-ORDONNANCEMENT DES ELEMENTS DE TEMPLATES 
template-hooks:

# FORMULAIRE
forms:
  ## Remplacement de la liste des pays select2 par tify_dropdown
  tify_dropdown_country:        false

# BOUTIQUE MULTIPLE
multishop:                      false

# PLATEFORMES DE PAIEMENT
payment_gateway:
  WC_Gateway_BACS:      true
  WC_Gateway_Cheque:    true
  WC_Gateway_COD:       true
  WC_Gateway_Paypal:    true
  Custom:               true
  
# COMMANDE
checkout:
  mininum_purchase:    
    ## Montant requis
    rate:               0
    ## Message d'erreur - %s reprend le montant minimum et la devise
    notice:             "<?php _e( 'Désolé, le montant minimum des commandes est fixé à %s', 'tify' );?>"
# Chargement des templates avec le moteur de gabarit PHP Plates
## Définition du service à charger
template_loader: